### ISSUE TITLE
Support Brainfuck Interpreter Sample Program

### ISSUE THREAD

**Issue by sunjay** [sunjay/dino#66]
There is a brainfuck interpreter sample program here:

https://github.com/sunjay/dino/blob/3f5812ee9539933ab23364d7367a89e92396bf79/tests/run-pass/todo/brainfuck.dino#L1-L283

To support compiling this program we need the features listed below. Some features can be considered optional as versions of the final program can be written using workarounds if not all features are ready yet.

## Language Features

- [ ] functions
- [ ] struct declarations and struct literals
- [ ] if statements as expressions
- [ ] static methods (for constructors)
- [ ] method dispatch (on `Self` type)
- [ ] simple enums without fields (#62)
- [ ] importing all variants of an enum into the current scope
    - [ ] optional: can be avoided by prefixing variants with enum name + `::`
- [ ] pattern matching
- [ ] `while let` loops
    - [ ] optional: desugar as `while true` + `match`
- [ ] explicit mutability (`let mut` and `mut self`)
    - [ ] optional: can be avoided simply by deleting the `mut` keyword from all of its uses
- [ ] 

## Primitives & Standard Library

- [ ] dynamically-sized `int` and `uint` types
- [ ] explicitly-sized numeric types (at least `u8`)
    - [ ] wrapping arithmetic
- [ ] lists of bytes `[u8]` (#36)
    - [ ] `len` method to get the length of the list
    - [ ] indexing and slicing into lists
- [ ] the `text` type (#43, #3)
    - [ ] `len` method to get the length of the text
    - [ ] slicing into lists but **no indexing** (since UTF-8)
- [ ] `io::write_byte(byte: u8)`
- [ ] `io::read_line_bytes() -> text` (should this return `[u8]`?)
